Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Word2Vec modeling. 
# model = Word2Vec(sentences=common_texts, vector_size=100, window=5, min_count=1, workers=4)
model_X_word2vec = Word2Vec(sentences=X_array, vector_size=100, window=5, min_count=1, workers=4)
------------------


[0;31m[0m
[0;31mNameError[0mTraceback (most recent call last)
[0;32m<ipython-input-33-7af1facd8dd8>[0m in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [0;31m# Word2Vec modeling.[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;31m# model = Word2Vec(sentences=common_texts, vector_size=100, window=5, min_count=1, workers=4)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mmodel_X_word2vec[0m [0;34m=[0m [0mWord2Vec[0m[0;34m([0m[0msentences[0m[0;34m=[0m[0mX_array[0m[0;34m,[0m [0mvector_size[0m[0;34m=[0m[0;36m100[0m[0;34m,[0m [0mwindow[0m[0;34m=[0m[0;36m5[0m[0;34m,[0m [0mmin_count[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m [0mworkers[0m[0;34m=[0m[0;36m4[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'X_array' is not defined

